In [1]:
import jax
import jax.numpy as jnp

In [6]:
x = jnp.arange(5)
y = jnp.arange(7)
print(x)
print(jnp.stack([x, 7]))

[0 1 2 3 4]


ValueError: All input arrays must have the same shape.

In [8]:
a = jnp.arange(5)
b = jnp.arange(5)
print(a)
print(b)
print(a @ b)

[0 1 2 3 4]
[0 1 2 3 4]
30


In [9]:
jax.local_device_count()

1

In [20]:
jax.devices()

[MetalDevice(id=0, process_index=0)]