In [9]:
import torch
print(dir(torch.version))
print(torch.version.cuda)
print(torch.__version__)
print(torch.version.__version__)

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'cuda', 'debug', 'git_version', 'hip']
None
2.1.0
2.1.0


In [56]:
a=torch.tensor([[1,2,3], [4,5,6]]) # give exact python array.
print(a.dtype) # int64 on my notebook.
a=torch.FloatTensor([[1,2,3], [4,5,6]]) # make it float
print(a.dtype) # flaot32
print(a.shape)
print(a)
print(a.dtype)
# indexing and slicing
print(a[1][1])
print(a[:, :2]) # how is this a valid syntax? it can't be done on py list. try impl this override.

a = torch.rand((4,5))
b = torch.ones((4,5))
print(a)
print(b)
print(a + b)

x = a.view((2, 10))
y = a.reshape((1,20))
y

torch.int64
torch.float32
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor(5.)
tensor([[1., 2.],
        [4., 5.]])
tensor([[0.7081, 0.4124, 0.1700, 0.0475, 0.3198],
        [0.1559, 0.9751, 0.3151, 0.6193, 0.3132],
        [0.0086, 0.7936, 0.3779, 0.7357, 0.2023],
        [0.6642, 0.2110, 0.1180, 0.5237, 0.5583]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1.7081, 1.4124, 1.1700, 1.0475, 1.3198],
        [1.1559, 1.9751, 1.3151, 1.6193, 1.3132],
        [1.0086, 1.7936, 1.3779, 1.7357, 1.2023],
        [1.6642, 1.2110, 1.1180, 1.5237, 1.5583]])


tensor([[0.7081, 0.4124, 0.1700, 0.0475, 0.3198, 0.1559, 0.9751, 0.3151, 0.6193,
         0.3132, 0.0086, 0.7936, 0.3779, 0.7357, 0.2023, 0.6642, 0.2110, 0.1180,
         0.5237, 0.5583]])

In [28]:
torch.zeros(1,2,3,4,5).dtype

torch.float32

In [60]:
# matmul
a = torch.rand(7,7)
b = torch.rand(7,7)
c = a @ b @ a @ b @ b @ a @ b @ b
print(c.shape)
print(c)

torch.Size([7, 7])
tensor([[4017.5310, 5329.3281, 5575.6206, 6816.2061, 7003.6699, 5450.0151,
         8061.1221],
        [4255.8208, 5645.5049, 5906.5410, 7220.6152, 7419.1904, 5773.2896,
         8539.4072],
        [3279.0327, 4349.7031, 4550.7271, 5563.2637, 5716.2749, 4448.2026,
         6579.3555],
        [1857.6310, 2464.2317, 2578.2083, 3151.7666, 3238.4392, 2520.0034,
         3727.4055],
        [2763.8511, 3666.2432, 3835.5732, 4689.1021, 4818.0776, 3749.3040,
         5545.5264],
        [4107.6836, 5448.8931, 5700.6685, 6969.1196, 7160.7998, 5572.3086,
         8241.9707],
        [2858.6570, 3792.0735, 3967.3374, 4850.0591, 4983.4502, 3877.9365,
         5735.8857]])


In [62]:
print(c)
print(c.sum(0))

tensor([[4017.5310, 5329.3281, 5575.6206, 6816.2061, 7003.6699, 5450.0151,
         8061.1221],
        [4255.8208, 5645.5049, 5906.5410, 7220.6152, 7419.1904, 5773.2896,
         8539.4072],
        [3279.0327, 4349.7031, 4550.7271, 5563.2637, 5716.2749, 4448.2026,
         6579.3555],
        [1857.6310, 2464.2317, 2578.2083, 3151.7666, 3238.4392, 2520.0034,
         3727.4055],
        [2763.8511, 3666.2432, 3835.5732, 4689.1021, 4818.0776, 3749.3040,
         5545.5264],
        [4107.6836, 5448.8931, 5700.6685, 6969.1196, 7160.7998, 5572.3086,
         8241.9707],
        [2858.6570, 3792.0735, 3967.3374, 4850.0591, 4983.4502, 3877.9365,
         5735.8857]])
tensor([23140.2070, 30695.9785, 32114.6777, 39260.1328, 40339.8984, 31391.0605,
        46430.6719])


In [65]:
a = torch.rand((3,4,5))
b = torch.rand((3,4,7))
torch.cat([a, b], dim=2)

tensor([[[7.9765e-01, 5.8051e-01, 1.5462e-01, 7.7800e-01, 5.1621e-01,
          7.2440e-01, 7.0482e-01, 9.4960e-01, 8.3941e-01, 9.9335e-01,
          9.1860e-01, 4.5343e-01],
         [3.4318e-01, 6.6042e-01, 7.9242e-01, 1.1209e-01, 8.3455e-02,
          4.0912e-01, 7.9462e-01, 7.0781e-02, 6.1316e-01, 7.8667e-01,
          4.3240e-01, 3.0761e-01],
         [1.4118e-01, 1.9399e-01, 9.4604e-01, 2.5521e-01, 5.6341e-01,
          3.2927e-02, 1.4126e-01, 6.2290e-01, 6.5583e-01, 4.3304e-01,
          3.4987e-01, 9.6381e-01],
         [6.8916e-01, 5.7930e-01, 3.6467e-01, 7.9715e-01, 8.7407e-01,
          7.0359e-01, 3.1942e-01, 1.0737e-02, 3.3143e-01, 5.0315e-01,
          3.5769e-01, 4.7029e-01]],

        [[6.8203e-01, 7.3456e-01, 4.5447e-01, 6.7917e-01, 7.8758e-01,
          7.1340e-01, 3.3299e-01, 8.6356e-01, 3.1838e-03, 7.3141e-01,
          3.3192e-01, 3.7027e-01],
         [3.0635e-01, 8.2358e-01, 9.7793e-01, 8.5237e-01, 9.6905e-02,
          2.4229e-04, 9.8127e-01, 8.4138e-01, 3.4003e

In [76]:
a = torch.rand(4, 5)
b = torch.rand(4, 5)
print(torch.stack([a, b], dim=0).shape)
print(torch.stack([a, b], dim=1).shape)
print(torch.stack([a, b], dim=2).shape)

torch.Size([2, 4, 5])
torch.Size([4, 2, 5])
torch.Size([4, 5, 2])


In [82]:
# squeeze
a = torch.rand((4,5,1,1, 3))
a.squeeze().shape

torch.Size([4, 5, 3])

In [26]:
# import torch
import tinygrad as t


a = t.tensor.Tensor([3,4,5], dtype=t.helpers.dtypes.float)
print(a)
print(a.shape)
b = t.tensor.Tensor([3,4,5], dtype=t.helpers.dtypes.double)
print(b)

c = a * b
print(c)

<Tensor <LB METAL (3,) contig:True (<LoadOps.COPY: 3>, None)> on METAL with grad None>
(3,)
<Tensor <LB METAL (3,) contig:True (<LoadOps.COPY: 3>, None)> on METAL with grad None>
<Tensor <LB METAL (3,) contig:True (<BinaryOps.MUL: 3>, None)> on METAL with grad None>


In [9]:
import numpy as np
print(np.newaxis)

None
